# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/secp256k1/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/secp256k1/cmake/CheckStringOptionValue.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/secp256k1/cmake/CheckX86_64Assembly.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/secp256k1/cmake/FindValgrind.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/secp256k1/cmake/TryAppendCFlags.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/secp256k1/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckFlagCommonConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))

/Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/ffi/build-ios-device/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/ffi -B/Users/alekseypopkov/Doc/nostr_notes/nostr_notes/cpp/ffi/build-ios-device
