
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - build/**
    - .dart_tool/**
    - .idea/**
    - .vscode/**
# Make the analyzer ignore a certain rule.

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    # deprecated_member_use_from_same_package: false

spellcheck:
  known_words:
    - usecases
    - usecase
    - nostr
    - gathr
    - eose
