// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int deriveSharedKey(
    ffi.Pointer<ffi.UnsignedChar> privKey,
    ffi.Pointer<ffi.UnsignedChar> pubKey,
    ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>> result,
  ) {
    return _deriveSharedKey(privKey, pubKey, result);
  }

  late final _deriveSharedKeyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<ffi.UnsignedChar>,
            ffi.Pointer<ffi.UnsignedChar>,
            ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
          )
        >
      >('deriveSharedKey');
  late final _deriveSharedKey = _deriveSharedKeyPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.UnsignedChar>,
          ffi.Pointer<ffi.UnsignedChar>,
          ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
        )
      >();
}
