default_platform(:mac)

platform :mac do
  desc "Push a new build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    api_key_content = Base64.decode64(ENV['NOSTR_NOTES_APP_STORE_CONNECT_API_KEY_BASE64'])

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: api_key_content
    )

    latest_build = latest_testflight_build_number(
      api_key: api_key,
      platform: "osx",
      initial_build_number: 0
    )
    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Runner.xcodeproj"
    )

    match(
      type: "appstore",
      platform: "macos",
      readonly: true,
      git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
      api_key: api_key
    )

    build_mac_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' DEVELOPMENT_TEAM='HCYSG3HDXK' PROVISIONING_PROFILE_SPECIFIER='match AppStore com.alekseii.yu.popkov.nostrNotes macos'"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
