# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "Runner.xcodeproj")
#     build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
#     upload_to_testflight
#   end
# end

platform :ios do
  desc "Push a new build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    # Decode API key from base64
    api_key_content = Base64.decode64(ENV['NOSTR_NOTES_APP_STORE_CONNECT_API_KEY_BASE64'])

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: api_key_content
    )

    latest_build = latest_testflight_build_number(
      api_key: api_key,
      initial_build_number: 0
    )
    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Runner.xcodeproj"
    )

    match(
      type: "appstore",
      readonly: true,
      git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
      api_key: api_key
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.alekseii.yu.popkov.nostrNotes" => "match AppStore com.alekseii.yu.popkov.nostrNotes"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end