name: Deploy Flutter Web to GH Pages Repo

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

# on:
#   workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6' 

      - name: Install melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: melos bootstrap

      - name: Build web
        working-directory: packages/notes
        run: flutter build web --release

      # - name: Setup SSH key
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.DEPLOY_GH_PAGES }}

      - name: Deploy to GH Pages repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_GH_PAGES }}
          publish_dir: ./packages/notes/build/web
          external_repository: AlexeyYuPopkov/AlexeyYuPopkov.github.io
          publish_branch: master   
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
